version: '3.9'

services:
  patient-service-db:
    image: postgres:15
    container_name: patient-service-db
    restart: always
    environment:
      POSTGRES_DB: patient
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    networks:
      - microservices-net

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    depends_on:
      - patient-service-db
      - kafka
    ports:
      - "4000:4000"
    networks:
      - microservices-net
    environment:
      # Kafka
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.ByteArraySerializer
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

      # App
      SPRING_APPLICATION_NAME: patient-service
      SERVER_PORT: 4000
      LOGGING_LEVEL_ROOT: info

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    depends_on:
      - patient-service-db
      - kafka
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge
