version: '3.9'

services:
  patient-service-db:
    image: postgres:15
    container_name: patient-service-db
    restart: always
    environment:
      POSTGRES_DB: patient
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - microservices-net

  auth-service-db:
    image: postgres:15
    container_name: auth-service-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - microservices-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    networks:
      - microservices-net

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    depends_on:
      - patient-service-db
      - kafka
    networks:
      - microservices-net
    environment:
      # Kafka
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.ByteArraySerializer
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

      # gRPC
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001

      # App
      SPRING_APPLICATION_NAME: patient-service
      SERVER_PORT: 4000
      LOGGING_LEVEL_ROOT: info

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    depends_on:
      - patient-service-db
      - kafka
    networks:
      - microservices-net
    environment:
      SPRING_APPLICATION_NAME: billing-service
      SERVER_PORT: 4001
      GRPC_SERVER_PORT: 9001

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    depends_on:
      - patient-service-db
      - kafka
    networks:
      - microservices-net
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.apache.kafka.common.serialization.ByteArrayDeserializer

      SPRING_APPLICATION_NAME: analytics-service
      SERVER_PORT: 4002
      LOGGING_LEVEL_ROOT: info

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - auth-service-db
    networks:
      - microservices-net
    environment:
      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

      # App
      SPRING_APPLICATION_NAME: auth-service
      SERVER_PORT: 4005
      LOGGING_LEVEL_ROOT: info
      JWT_SECRET: c770800082dc503ceb65137bb945dc37f4b49d30ae59aade779386242b4650933eb45d0c8deaefbcbc0a4c491f2692aefd846ed3f4169ad2baf518f730e95d08

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - auth-service
      - patient-service
    ports:
      - "4004:4004"
    networks:
      - microservices-net
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
      SPRING_APPLICATION_NAME: gateway
      SERVER_PORT: 4004
      LOGGING_LEVEL_ROOT: info

networks:
  microservices-net:
    driver: bridge
